require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiveCentersController do

  # This should return the minimal set of attributes required to create a valid
  # DiveCenter. As you add validations to DiveCenter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all dive_centers as @dive_centers" do
      dive_center = DiveCenter.create! valid_attributes
      get :index
      assigns(:dive_centers).should eq([dive_center])
    end
  end

  describe "GET show" do
    it "assigns the requested dive_center as @dive_center" do
      dive_center = DiveCenter.create! valid_attributes
      get :show, :id => dive_center.id.to_s
      assigns(:dive_center).should eq(dive_center)
    end
  end

  describe "GET new" do
    it "assigns a new dive_center as @dive_center" do
      get :new
      assigns(:dive_center).should be_a_new(DiveCenter)
    end
  end

  describe "GET edit" do
    it "assigns the requested dive_center as @dive_center" do
      dive_center = DiveCenter.create! valid_attributes
      get :edit, :id => dive_center.id.to_s
      assigns(:dive_center).should eq(dive_center)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DiveCenter" do
        expect {
          post :create, :dive_center => valid_attributes
        }.to change(DiveCenter, :count).by(1)
      end

      it "assigns a newly created dive_center as @dive_center" do
        post :create, :dive_center => valid_attributes
        assigns(:dive_center).should be_a(DiveCenter)
        assigns(:dive_center).should be_persisted
      end

      it "redirects to the created dive_center" do
        post :create, :dive_center => valid_attributes
        response.should redirect_to(DiveCenter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dive_center as @dive_center" do
        # Trigger the behavior that occurs when invalid params are submitted
        DiveCenter.any_instance.stub(:save).and_return(false)
        post :create, :dive_center => {}
        assigns(:dive_center).should be_a_new(DiveCenter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DiveCenter.any_instance.stub(:save).and_return(false)
        post :create, :dive_center => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dive_center" do
        dive_center = DiveCenter.create! valid_attributes
        # Assuming there are no other dive_centers in the database, this
        # specifies that the DiveCenter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DiveCenter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => dive_center.id, :dive_center => {'these' => 'params'}
      end

      it "assigns the requested dive_center as @dive_center" do
        dive_center = DiveCenter.create! valid_attributes
        put :update, :id => dive_center.id, :dive_center => valid_attributes
        assigns(:dive_center).should eq(dive_center)
      end

      it "redirects to the dive_center" do
        dive_center = DiveCenter.create! valid_attributes
        put :update, :id => dive_center.id, :dive_center => valid_attributes
        response.should redirect_to(dive_center)
      end
    end

    describe "with invalid params" do
      it "assigns the dive_center as @dive_center" do
        dive_center = DiveCenter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DiveCenter.any_instance.stub(:save).and_return(false)
        put :update, :id => dive_center.id.to_s, :dive_center => {}
        assigns(:dive_center).should eq(dive_center)
      end

      it "re-renders the 'edit' template" do
        dive_center = DiveCenter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DiveCenter.any_instance.stub(:save).and_return(false)
        put :update, :id => dive_center.id.to_s, :dive_center => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dive_center" do
      dive_center = DiveCenter.create! valid_attributes
      expect {
        delete :destroy, :id => dive_center.id.to_s
      }.to change(DiveCenter, :count).by(-1)
    end

    it "redirects to the dive_centers list" do
      dive_center = DiveCenter.create! valid_attributes
      delete :destroy, :id => dive_center.id.to_s
      response.should redirect_to(dive_centers_url)
    end
  end

end
